<?php

/**
 * @file
 * cmlmigrations.module
 */

use Drupal\node\NodeInterface;
use Drupal\cmlmigrations\Controller\FixVariation;

/**
 * Hook_entity_presave.
 */
function cmlmigrations_node_presave(NodeInterface $node) {
  FixVariation::fixVariations($node);
}

/**
 * Hook_entity_presave.
 */
function cmlmigrations_node_insert(NodeInterface $node) {
  // FixVariation::setVariations($node);
}

/**
 * Hook_entity_presave.
 */
function cmlmigrations_node_view(&$build, NodeInterface $node, $display, $view_mode) {
  // FixVariation::setVariations($node);
}
